### ISSUE TITLE
Can't bundle

### ISSUE THREAD

**Issue by jonathanfishbein1** [Felippo001/nami-wallet-api#3]
node-fetch is causing problems with webpack and parcel because of the node: prefix

`Uncaught (in promise) Error: Cannot find module 'http'
    at newRequire (index.bdea7d65.js:61)
    at newRequire (cardano_serialization_lib.a9c0fc35.js?1638554532050:53)
    at newRequire (buffer.a8023b95.js?1638554532848:53)
    at newRequire (buffer.a8023b95.js?1638554532870:53)
    at newRequire (node-fetch.0d50a49d.js?1638554532871:53)
    at newRequire (node-fetch.0d50a49d.js?1638554532871:45)
    at localRequire (node-fetch.0d50a49d.js?1638554532871:83)
    at Object.drwRt.buffer (index.js:9)
    at Function.newRequire (node-fetch.0d50a49d.js?1638554532871:71)
    at runtime-f61b6616eb6f623a.js:1`
node v17.1.0
yarn v1.22.17
NixOS
parcel : latest

this is the error message using webpack
`ERROR in node:http
Module build failed: UnhandledSchemeError: Reading from "node:http" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /home/jonathan/Documents/namiTwo/node_modules/webpack/lib/NormalModule.js:825:25
    at Hook.eval [as callAsync] (eval at create (/home/jonathan/Documents/namiTwo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/jonathan/Documents/namiTwo/node_modules/tapable/lib/Hook.js:18:14)
    at Object.processResource (/home/jonathan/Documents/namiTwo/node_modules/webpack/lib/NormalModule.js:822:8)
    at processResource (/home/jonathan/Documents/namiTwo/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/home/jonathan/Documents/namiTwo/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/home/jonathan/Documents/namiTwo/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule._doBuild (/home/jonathan/Documents/namiTwo/node_modules/webpack/lib/NormalModule.js:812:3)
    at NormalModule.build (/home/jonathan/Documents/namiTwo/node_modules/webpack/lib/NormalModule.js:956:15)
    at /home/jonathan/Documents/namiTwo/node_modules/webpack/lib/Compilation.js:1367:12
 @ ./node_modules/node-fetch/src/index.js 9:0-29 52:58-62
 @ ./node_modules/nami-wallet-api/lib/index.js 645:98-119
 @ ./src/index.js 1:0-38`

here's my dependencies in the package.json file
`  "devDependencies": {
    "html-loader": "^2.1.2",
    "html-webpack-plugin": "^5.3.2",
    "webpack": "^5.64.4",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.6.0"
  },
  "dependencies": {
    "nami-wallet-api": "^1.1.9",
    "node-fetch": "^3.1.0"
  }`

this issue seems similar
https://github.com/parcel-bundler/parcel/issues/7387

**Comment by jonathanfishbein1** [comment]
Use node-fetch 2.6.6 and it works
